'''
Created on Feb 15, 2023

@author: IterationFive
'''
glyphs  = {
    'bbss' : 'ACS_BBSS',
    'block' : 'ACS_BLOCK',
    'board' : 'ACS_BOARD',
    'bsbs' : 'ACS_BSBS',
    'bssb' : 'ACS_BSSB',
    'bsss' : 'ACS_BSSS',
    'btee' : 'ACS_BTEE',
    'bullet' : 'ACS_BULLET',
    'ckboard' : 'ACS_CKBOARD',
    'darrow' : 'ACS_DARROW',
    'degree' : 'ACS_DEGREE',
    'diamond' : 'ACS_DIAMOND',
    'gequal' : 'ACS_GEQUAL',
    'hline' : 'ACS_HLINE',
    'lantern' : 'ACS_LANTERN',
    'larrow' : 'ACS_LARROW',
    'lequal' : 'ACS_LEQUAL',
    'llcorner' : 'ACS_LLCORNER',
    'lrcorner' : 'ACS_LRCORNER',
    'ltee' : 'ACS_LTEE',
    'nequal' : 'ACS_NEQUAL',
    'pi' : 'ACS_PI',
    'plminus' : 'ACS_PLMINUS',
    'plus' : 'ACS_PLUS',
    'rarrow' : 'ACS_RARROW',
    'rtee' : 'ACS_RTEE',
    's1' : 'ACS_S1',
    's3' : 'ACS_S3',
    's7' : 'ACS_S7',
    's9' : 'ACS_S9',
    'sbbs' : 'ACS_SBBS',
    'sbsb' : 'ACS_SBSB',
    'sbss' : 'ACS_SBSS',
    'ssbb' : 'ACS_SSBB',
    'ssbs' : 'ACS_SSBS',
    'sssb' : 'ACS_SSSB',
    'ssss' : 'ACS_SSSS',
    'sterling' : 'ACS_STERLING',
    'ttee' : 'ACS_TTEE',
    'uarrow' : 'ACS_UARROW',
    'ulcorner' : 'ACS_ULCORNER',
    'urcorner' : 'ACS_URCORNER',
    'vline' : 'ACS_VLINE',
    'euro': 128,
    'copyright': 169,
    'squared': 178,
    'cubed' :179,
    'onequarter':188,
    'onehalf': 189,
    'threequarters': 190,
    'yen': 165,
    'divisor': 247,
    '<<': 171,
    '>>': 187,
    'up?': 191,
    'cent': 162, 
    'paragraph': 182,
    'section': 167
}